let libros=[
    {   titulo:'Don Quijote de la Mancha',
        autor:'Miguel de Cervantes',
        genero:'ficcion',
        idioma:'Español',
        precio:'15000$',
        formato:'Tapa blanda',
        isbn:'10',
        descripcion:'Relata las aventuras y desventuras de un hidalgo de 50 años llamado Alonso Quijano, quien decide ser un caballero andante como aquellos que aparecen en sus libros de caballerías favoritos.',
        estado:'Nuevo',
        ubicacion:'Colombia',
        fecha_publicacion:1868,
        editorial:'Urbano Manini',
        paginas:'1056',
        dimensiones:'6 x 1.05 x 9 pulgadas',
        peso:'50 grs',
    },
    {
        titulo:'',
        autor:'Miguel de Cervantes',
        genero:'ficcion',
        idioma:'Español',
        precio:'15000$',
        formato:'Tapa blanda',
        isbn:'10',
        descripcion:'',
        estado:'Nuevo',
        ubicacion:'Colombia',
        fecha_publicacion:1868,
        editorial:'Urbano Manini',
        paginas:'1056',
        dimensiones:'6 x 1.05 x 9 pulgadas',
        peso:'50 grs',
    },
    {
        titulo:'Don Quijote de la Mancha',
        autor:'Miguel de Cervantes',
        genero:'ficcion',
        idioma:'Español',
        precio:'15000$',
        formato:'Tapa blanda',
        isbn:'10',
        descripcion:'',
        estado:'Nuevo',
        ubicacion:'Colombia',
        fecha_publicacion:1868,
        editorial:'Urbano Manini',
        paginas:'1056',
        dimensiones:'6 x 1.05 x 9 pulgadas',
        peso:'50 grs',
    },
    {
        titulo:'Don Quijote de la Mancha',
        autor:'Miguel de Cervantes',
        genero:'ficcion',
        idioma:'Español',
        precio:'15000$',
        formato:'Tapa blanda',
        isbn:'10',
        descripcion:'',
        estado:'Nuevo',
        ubicacion:'Colombia',
        fecha_publicacion:1868,
        editorial:'Urbano Manini',
        paginas:'1056',
        dimensiones:'6 x 1.05 x 9 pulgadas',
        peso:'50 grs',
    },
    {
        titulo:'Don Quijote de la Mancha',
        autor:'Miguel de Cervantes',
        genero:'ficcion',
        idioma:'Español',
        precio:'15000$',
        formato:'Tapa blanda',
        isbn:'10',
        descripcion:'',
        estado:'Nuevo',
        ubicacion:'Colombia',
        fecha_publicacion:1868,
        editorial:'Urbano Manini',
        paginas:'1056',
        dimensiones:'6 x 1.05 x 9 pulgadas',
        peso:'50 grs',
    },
    {
        titulo:'Don Quijote de la Mancha',
        autor:'Miguel de Cervantes',
        genero:'ficcion',
        idioma:'Español',
        precio:'15000$',
        formato:'Tapa blanda',
        isbn:'10',
        descripcion:'',
        estado:'Nuevo',
        ubicacion:'Colombia',
        fecha_publicacion:1868,
        editorial:'Urbano Manini',
        paginas:'1056',
        dimensiones:'6 x 1.05 x 9 pulgadas',
        peso:'50 grs',
    },
    {
        titulo:'Don Quijote de la Mancha',
        autor:'Miguel de Cervantes',
        genero:'ficcion',
        idioma:'Español',
        precio:'15000$',
        formato:'Tapa blanda',
        isbn:'10',
        descripcion:'',
        estado:'Nuevo',
        ubicacion:'Colombia',
        fecha_publicacion:1868,
        editorial:'Urbano Manini',
        paginas:'1056',
        dimensiones:'6 x 1.05 x 9 pulgadas',
        peso:'50 grs',
    },
    {
        titulo:'Don Quijote de la Mancha',
        autor:'Miguel de Cervantes',
        genero:'ficcion',
        idioma:'Español',
        precio:'15000$',
        formato:'Tapa blanda',
        isbn:'10',
        descripcion:'',
        estado:'Nuevo',
        ubicacion:'Colombia',
        fecha_publicacion:1868,
        editorial:'Urbano Manini',
        paginas:'1056',
        dimensiones:'6 x 1.05 x 9 pulgadas',
        peso:'50 grs',
    },
    {
        titulo:'Don Quijote de la Mancha',
        autor:'Miguel de Cervantes',
        genero:'ficcion',
        idioma:'Español',
        precio:'15000$',
        formato:'Tapa blanda',
        isbn:'10',
        descripcion:'',
        estado:'Nuevo',
        ubicacion:'Colombia',
        fecha_publicacion:1868,
        editorial:'Urbano Manini',
        paginas:'1056',
        dimensiones:'6 x 1.05 x 9 pulgadas',
        peso:'50 grs',
    },
    {
        titulo:'Don Quijote de la Mancha',
        autor:'Miguel de Cervantes',
        genero:'ficcion',
        idioma:'Español',
        precio:'15000$',
        formato:'Tapa blanda',
        isbn:'10',
        descripcion:'',
        estado:'Nuevo',
        ubicacion:'Colombia',
        fecha_publicacion:1868,
        editorial:'Urbano Manini',
        paginas:'1056',
        dimensiones:'6 x 1.05 x 9 pulgadas',
        peso:'50 grs',
    },
    {
        titulo:'Don Quijote de la Mancha',
        autor:'Miguel de Cervantes',
        genero:'ficcion',
        idioma:'Español',
        precio:'15000$',
        formato:'Tapa blanda',
        isbn:'10',
        descripcion:'',
        estado:'Nuevo',
        ubicacion:'Colombia',
        fecha_publicacion:1868,
        editorial:'Urbano Manini',
        paginas:'1056',
        dimensiones:'6 x 1.05 x 9 pulgadas',
        peso:'50 grs',
    },
    {
        titulo:'Don Quijote de la Mancha',
        autor:'Miguel de Cervantes',
        genero:'ficcion',
        idioma:'Español',
        precio:'15000$',
        formato:'Tapa blanda',
        isbn:'10',
        descripcion:'',
        estado:'Nuevo',
        ubicacion:'Colombia',
        fecha_publicacion:1868,
        editorial:'Urbano Manini',
        paginas:'1056',
        dimensiones:'6 x 1.05 x 9 pulgadas',
        peso:'50 grs',
    },
    {
        titulo:'Don Quijote de la Mancha',
        autor:'Miguel de Cervantes',
        genero:'ficcion',
        idioma:'Español',
        precio:'15000$',
        formato:'Tapa blanda',
        isbn:'10',
        descripcion:'',
        estado:'Nuevo',
        ubicacion:'Colombia',
        fecha_publicacion:1868,
        editorial:'Urbano Manini',
        paginas:'1056',
        dimensiones:'6 x 1.05 x 9 pulgadas',
        peso:'50 grs',
    },
    {
        titulo:'Don Quijote de la Mancha',
        autor:'Miguel de Cervantes',
        genero:'ficcion',
        idioma:'Español',
        precio:'15000$',
        formato:'Tapa blanda',
        isbn:'10',
        descripcion:'',
        estado:'Nuevo',
        ubicacion:'Colombia',
        fecha_publicacion:1868,
        editorial:'Urbano Manini',
        paginas:'1056',
        dimensiones:'6 x 1.05 x 9 pulgadas',
        peso:'50 grs',
    },
    {
        titulo:'Don Quijote de la Mancha',
        autor:'Miguel de Cervantes',
        genero:'ficcion',
        idioma:'Español',
        precio:'15000$',
        formato:'Tapa blanda',
        isbn:'10',
        descripcion:'',
        estado:'Nuevo',
        ubicacion:'Colombia',
        fecha_publicacion:1868,
        editorial:'Urbano Manini',
        paginas:'1056',
        dimensiones:'6 x 1.05 x 9 pulgadas',
        peso:'50 grs',
    },
    {
        titulo:'Don Quijote de la Mancha',
        autor:'Miguel de Cervantes',
        genero:'ficcion',
        idioma:'Español',
        precio:'15000$',
        formato:'Tapa blanda',
        isbn:'10',
        descripcion:'',
        estado:'Nuevo',
        ubicacion:'Colombia',
        fecha_publicacion:1868,
        editorial:'Urbano Manini',
        paginas:'1056',
        dimensiones:'6 x 1.05 x 9 pulgadas',
        peso:'50 grs',
    },
    {
        titulo:'Don Quijote de la Mancha',
        autor:'Miguel de Cervantes',
        genero:'ficcion',
        idioma:'Español',
        precio:'15000$',
        formato:'Tapa blanda',
        isbn:'10',
        descripcion:'',
        estado:'Nuevo',
        ubicacion:'Colombia',
        fecha_publicacion:1868,
        editorial:'Urbano Manini',
        paginas:'1056',
        dimensiones:'6 x 1.05 x 9 pulgadas',
        peso:'50 grs',
    },
    {
        titulo:'Don Quijote de la Mancha',
        autor:'Miguel de Cervantes',
        genero:'ficcion',
        idioma:'Español',
        precio:'15000$',
        formato:'Tapa blanda',
        isbn:'10',
        descripcion:'',
        estado:'Nuevo',
        ubicacion:'Colombia',
        fecha_publicacion:1868,
        editorial:'Urbano Manini',
        paginas:'1056',
        dimensiones:'6 x 1.05 x 9 pulgadas',
        peso:'50 grs',
    },
    {
        titulo:'Don Quijote de la Mancha',
        autor:'Miguel de Cervantes',
        genero:'ficcion',
        idioma:'Español',
        precio:'15000$',
        formato:'Tapa blanda',
        isbn:'10',
        descripcion:'',
        estado:'Nuevo',
        ubicacion:'Colombia',
        fecha_publicacion:1868,
        editorial:'Urbano Manini',
        paginas:'1056',
        dimensiones:'6 x 1.05 x 9 pulgadas',
        peso:'50 grs',
    },
    {
        titulo:'Don Quijote de la Mancha',
        autor:'Miguel de Cervantes',
        genero:'ficcion',
        idioma:'Español',
        precio:'15000$',
        formato:'Tapa blanda',
        isbn:'10',
        descripcion:'',
        estado:'Nuevo',
        ubicacion:'Colombia',
        fecha_publicacion:1868,
        editorial:'Urbano Manini',
        paginas:'1056',
        dimensiones:'6 x 1.05 x 9 pulgadas',
        peso:'50 grs',
    },
    ];
    let new_book={
        titulo:'Harry Potter',
        autor:'Miguel de Cervantes',
        genero:'ficcion',
        idioma:'Español',
        precio:'15000$',
        formato:'Tapa blanda',
        isbn:'10',
        descripcion:'',
        estado:'Nuevo',
        ubicacion:'Colombia',
        fecha_publicacion:1868,
        editorial:'Urbano Manini',
        paginas:'1056',
        dimensiones:'6 x 1.05 x 9 pulgadas',
        peso:'50 grs',
    }
    
    libros.push(new_book);
    console.log(libros);
    let ultimo_libro=libros.pop();
    console.log(ultimo_libro);